name: 嘉立创自动签到主脚本

on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 01 * * *'  # 每天北京时间9点运行
    # 在这里设置UTC运行时间，如果不知道怎么配置可以问AI
    # 实际运行时间会比设置时间延迟一小时以内，取决于当时GitHub资源占用情况。

jobs:
  running:
    runs-on: ubuntu-22.04

    env: #注入推送相关的环境变量（从secrets读取）
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      WECHAT_WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
      DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
      PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
      SERVERCHAN_SCKEY: ${{ secrets.SERVERCHAN_SCKEY }}
      COOLPUSH_SKEY: ${{ secrets.COOLPUSH_SKEY }}
      CUSTOM_WEBHOOK: ${{ secrets.CUSTOM_WEBHOOK }}

    steps:
      - name: '检出代码'
        uses: actions/checkout@v3

      - name: '设置Python环境'
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: '设置时区为北京时间'
        run: |
          sudo timedatectl set-timezone Asia/Shanghai
          echo "当前时间: $(date)"

      - name: '安装依赖'
        run: |
          pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: '准备Chrome驱动'
        uses: nanasess/setup-chromedriver@v2

      - name: '进行签到流程(日志在这里看)'
        run: |
          python ./jlc.py "${{ secrets.JLC_USERNAME }}" "${{ secrets.JLC_PASSWORD }}" "${{ secrets.ERROR }}"
